# Generated by Django 6.1 on 2026-09-29 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0007_alter_employee_delegation_alter_employee_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('period_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(verbose_name='End date')),
                ('computable_days', models.IntegerField(verbose_name='Computable days')),
                ('status', models.CharField(default='Active', max_length=50, verbose_name='Status')),
                ('thresholds', models.CharField(max_length=255, verbose_name='Thresholds')),
                ('parameters_version', models.CharField(max_length=50, verbose_name='Parameters version')),
            ],
            options={
                'verbose_name': 'Period',
                'verbose_name_plural': 'Periods',
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('goal_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=150, verbose_name='Item')),
                ('objective_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Objective value')),
                ('unit', models.CharField(max_length=50, verbose_name='Unit')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Weight')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goals', to='organization.employee', verbose_name='Employee')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goals', to='organization.positionfunction', verbose_name='Position')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goals', to='planning_measurements.period', verbose_name='Period')),
            ],
            options={
                'verbose_name': 'Goal',
                'verbose_name_plural': 'Goals',
            },
        ),
    ]
