# Generated by Django 6.1 on 2026-09-28 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0004_remove_funcionario_identificador_institucional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id_periodo', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(verbose_name='Inicio')),
                ('fecha_termino', models.DateField(verbose_name='Término')),
                ('dias_computables', models.IntegerField(verbose_name='Días computables')),
                ('estado', models.CharField(default='Activo', max_length=50, verbose_name='Estado')),
                ('umbrales', models.CharField(max_length=255, verbose_name='Umbrales')),
                ('version_parametros', models.CharField(max_length=50, verbose_name='Versión de parámetros')),
            ],
            options={
                'verbose_name': 'Período',
                'verbose_name_plural': 'Períodos',
            },
        ),
        migrations.CreateModel(
            name='MetaDesempeno',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id_meta', models.BigAutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=150, verbose_name='Ítem')),
                ('valor_objetivo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor objetivo')),
                ('unidad', models.CharField(max_length=50, verbose_name='Unidad')),
                ('ponderador', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Ponderador')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metas', to='organization.cargofuncion', verbose_name='Cargo')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metas', to='organization.funcionario')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metas', to='planning_measurements.periodo')),
            ],
            options={
                'verbose_name': 'Meta',
                'verbose_name_plural': 'Metas',
            },
        ),
    ]
