# Generated by Django 6.1 on 2026-09-29 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_alter_employee_delegation_alter_employee_position'),
        ('planning_measurements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('period_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(verbose_name='Inicio')),
                ('end_date', models.DateField(verbose_name='Término')),
                ('computable_days', models.IntegerField(verbose_name='Días computables')),
                ('status', models.CharField(default='Activo', max_length=50, verbose_name='Estado')),
                ('thresholds', models.CharField(max_length=255, verbose_name='Umbrales')),
                ('parameters_version', models.CharField(max_length=50, verbose_name='Versión de parámetros')),
            ],
            options={
                'verbose_name': 'Período',
                'verbose_name_plural': 'Períodos',
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('goal_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=150, verbose_name='Ítem')),
                ('objective_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor objetivo')),
                ('unit', models.CharField(max_length=50, verbose_name='Unidad')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Ponderador')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goals', to='organization.employee', verbose_name='Funcionario')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goals', to='organization.positionfunction', verbose_name='Cargo')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goals', to='planning_measurements.period', verbose_name='Período')),
            ],
            options={
                'verbose_name': 'Meta',
                'verbose_name_plural': 'Metas',
            },
        ),
        migrations.DeleteModel(
            name='MetaDesempeno',
        ),
        migrations.DeleteModel(
            name='Periodo',
        ),
    ]
