# Generated by Django 6.1 on 2026-09-29 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_alter_employee_delegation_alter_employee_position'),
        ('planning_measurements', '0002_period_goal_delete_metadesempeno_delete_periodo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'verbose_name': 'Goal', 'verbose_name_plural': 'Goals'},
        ),
        migrations.AlterModelOptions(
            name='period',
            options={'verbose_name': 'Period', 'verbose_name_plural': 'Periods'},
        ),
        migrations.AlterField(
            model_name='goal',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goals', to='organization.employee', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='item',
            field=models.CharField(max_length=150, verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='objective_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Objective value'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goals', to='planning_measurements.period', verbose_name='Period'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goals', to='organization.positionfunction', verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='unit',
            field=models.CharField(max_length=50, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='period',
            name='computable_days',
            field=models.IntegerField(verbose_name='Computable days'),
        ),
        migrations.AlterField(
            model_name='period',
            name='end_date',
            field=models.DateField(verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='period',
            name='parameters_version',
            field=models.CharField(max_length=50, verbose_name='Parameters version'),
        ),
        migrations.AlterField(
            model_name='period',
            name='start_date',
            field=models.DateField(verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='period',
            name='status',
            field=models.CharField(default='Active', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='period',
            name='thresholds',
            field=models.CharField(max_length=255, verbose_name='Thresholds'),
        ),
    ]
