# Generated by Django 6.1 on 2026-09-26 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoFuncion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id_cargo', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_cargo', models.CharField(max_length=150)),
                ('items_medibles', models.TextField()),
                ('servicios', models.TextField()),
                ('ponderaciones', models.TextField()),
                ('vigencia_inicio', models.DateField()),
                ('vigencia_fin', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Delegacion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id_delegacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('estado', models.CharField(max_length=50)),
                ('ambito', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id_funcionario', models.BigAutoField(primary_key=True, serialize=False)),
                ('identificador_institucional', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('roles', models.TextField()),
                ('estado', models.CharField(max_length=50)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='organization.cargofuncion')),
                ('delegacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='organization.delegacion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
