# Generated by Django 6.1 on 2026-09-26 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_cargofuncion_delegacion_funcionario_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargofuncion',
            options={'verbose_name': 'Cargo y Función', 'verbose_name_plural': 'Cargos y Funciones'},
        ),
        migrations.AlterModelOptions(
            name='delegacion',
            options={'verbose_name': 'Delegación', 'verbose_name_plural': 'Delegaciones'},
        ),
        migrations.AlterModelOptions(
            name='funcionario',
            options={'verbose_name': 'Funcionario', 'verbose_name_plural': 'Funcionarios'},
        ),
    ]
