# Generated by Django 6.1 on 2026-09-27 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_alter_cargofuncion_options_alter_delegacion_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='identificador_institucional',
        ),
    ]
