# Generated by Django 6.1 on 2026-09-29 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0005_rename_fields_english"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Delegacion",
            new_name="Delegation",
        ),
        migrations.RenameModel(
            old_name="CargoFuncion",
            new_name="PositionFunction",
        ),
        migrations.RenameModel(
            old_name="Funcionario",
            new_name="Employee",
        ),
        migrations.AlterModelOptions(
            name="delegation",
            options={
                "verbose_name": "Delegation",
                "verbose_name_plural": "Delegations",
            },
        ),
        migrations.AlterModelOptions(
            name="positionfunction",
            options={
                "verbose_name": "Position and Role",
                "verbose_name_plural": "Positions and Roles",
            },
        ),
        migrations.AlterModelOptions(
            name="employee",
            options={
                "verbose_name": "Employee",
                "verbose_name_plural": "Employees",
            },
        ),
    ]