# Generated by Django 6.1 on 2026-09-29 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_alter_delegation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='delegation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='organization.delegation'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='organization.positionfunction'),
        ),
    ]
