# Generated by Django 6.1 on 2026-10-07 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organization', '0007_alter_employee_delegation_alter_employee_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionfunction',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='auth.group', verbose_name='Grupo de permisos'),
        ),
    ]
