# Generated by Django 6.1 on 2026-09-30 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0007_alter_employee_delegation_alter_employee_position'),
        ('planning_measurements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('activity_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID actividad')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('request_problem', models.TextField(verbose_name='Solicitud o problema')),
                ('action', models.TextField(verbose_name='Acción')),
                ('contact', models.CharField(max_length=150, verbose_name='Contacto')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('status', models.CharField(default='Pending', max_length=50, verbose_name='Estado')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities_created', to='organization.employee', verbose_name='Autor')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='planning_measurements.goal', verbose_name='Meta')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ('-date', 'activity_id'),
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('evidence_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID evidencia')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Código')),
                ('file_link', models.CharField(max_length=500, verbose_name='Archivo o vínculo')),
                ('date', models.DateTimeField(verbose_name='Fecha')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadatos')),
                ('review_status', models.CharField(default='Pending', max_length=50, verbose_name='Estado de revisión')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidences', to='registration_validation.activity', verbose_name='Actividad')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidences_created', to='organization.employee', verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Evidencia',
                'verbose_name_plural': 'Evidencias',
                'ordering': ('-date', 'evidence_id'),
            },
        ),
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('validation_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID validación')),
                ('decision', models.CharField(max_length=50, verbose_name='Decisión')),
                ('date', models.DateTimeField(verbose_name='Fecha')),
                ('observation', models.TextField(blank=True, verbose_name='Observación')),
                ('result', models.CharField(max_length=100, verbose_name='Resultado')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Versión')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='validations', to='registration_validation.evidence', verbose_name='Evidencia')),
                ('verifier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='validations_performed', to='organization.employee', verbose_name='Verificador')),
            ],
            options={
                'verbose_name': 'Validación',
                'verbose_name_plural': 'Validaciones',
                'ordering': ('-date', '-version'),
            },
        ),
    ]
