# Generated by Django 6.1 on 2026-09-30 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_alter_employee_delegation_alter_employee_position'),
        ('planning_measurements', '0001_initial'),
        ('registration_validation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ('-date', 'activity_id'), 'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='evidence',
            options={'ordering': ('-date', 'evidence_id'), 'verbose_name': 'Evidence', 'verbose_name_plural': 'Evidences'},
        ),
        migrations.AlterModelOptions(
            name='validation',
            options={'ordering': ('-date', '-version'), 'verbose_name': 'Validation', 'verbose_name_plural': 'Validations'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='action',
            field=models.TextField(verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='Activity ID'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities_created', to='organization.employee', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='contact',
            field=models.CharField(max_length=150, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='planning_measurements.goal', verbose_name='Goal'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='request_problem',
            field=models.TextField(verbose_name='Request or problem'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(default='Pending', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidences', to='registration_validation.activity', verbose_name='Activity'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidences_created', to='organization.employee', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='code',
            field=models.CharField(max_length=100, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='date',
            field=models.DateTimeField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='evidence_id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='Evidence ID'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='file_link',
            field=models.CharField(max_length=500, verbose_name='File or link'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Metadata'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='review_status',
            field=models.CharField(default='Pending', max_length=50, verbose_name='Review status'),
        ),
        migrations.AlterField(
            model_name='validation',
            name='date',
            field=models.DateTimeField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='validation',
            name='decision',
            field=models.CharField(max_length=50, verbose_name='Decision'),
        ),
        migrations.AlterField(
            model_name='validation',
            name='evidence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='validations', to='registration_validation.evidence', verbose_name='Evidence'),
        ),
        migrations.AlterField(
            model_name='validation',
            name='observation',
            field=models.TextField(blank=True, verbose_name='Observation'),
        ),
        migrations.AlterField(
            model_name='validation',
            name='result',
            field=models.CharField(max_length=100, verbose_name='Result'),
        ),
        migrations.AlterField(
            model_name='validation',
            name='validation_id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='Validation ID'),
        ),
        migrations.AlterField(
            model_name='validation',
            name='verifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='validations_performed', to='organization.employee', verbose_name='Verifier'),
        ),
        migrations.AlterField(
            model_name='validation',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='Version'),
        ),
    ]
