# Generated by Django 6.1 on 2026-09-29 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0007_alter_employee_delegation_alter_employee_position'),
        ('planning_measurements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('activity_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Activity reference',
                'verbose_name_plural': 'Activity references',
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('evidence_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Evidence reference',
                'verbose_name_plural': 'Evidence references',
            },
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('audit_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event', models.CharField(max_length=100, verbose_name='Event')),
                ('event_date', models.DateTimeField(auto_now_add=True, verbose_name='Event date')),
                ('entity', models.CharField(max_length=100, verbose_name='Entity')),
                ('object_identifier', models.CharField(max_length=100, verbose_name='Object identifier')),
                ('previous_value', models.JSONField(blank=True, null=True, verbose_name='Previous value')),
                ('new_value', models.JSONField(blank=True, null=True, verbose_name='New value')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='organization.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Audit event',
                'verbose_name_plural': 'Audit events',
                'ordering': ('-event_date', '-audit_id'),
            },
        ),
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('commitment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('requester', models.CharField(max_length=150, verbose_name='Requester')),
                ('territory', models.CharField(max_length=150, verbose_name='Territory')),
                ('commitment_date', models.DateField(verbose_name='Commitment date')),
                ('support', models.TextField(blank=True, verbose_name='Support')),
                ('status', models.CharField(default='Pending', max_length=50, verbose_name='Status')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commitments', to='monitoring_traceability.activity', verbose_name='Activity reference')),
                ('delegation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commitments', to='organization.delegation', verbose_name='Delegation')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commitments', to='organization.employee', verbose_name='Responsible employee')),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commitments', to='monitoring_traceability.evidence', verbose_name='Evidence reference')),
            ],
            options={
                'verbose_name': 'Commitment',
                'verbose_name_plural': 'Commitments',
                'ordering': ('-commitment_date', 'commitment_id'),
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('indicator_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('expected_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Expected value')),
                ('actual_progress', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Actual progress')),
                ('green_progress', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Green progress')),
                ('difference', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Difference')),
                ('compliance', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Compliance')),
                ('weighting', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Weighting')),
                ('adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Adjustment')),
                ('traffic_light', models.CharField(max_length=30, verbose_name='Traffic light')),
                ('calculation_date', models.DateField(verbose_name='Calculation date')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indicators', to='organization.employee', verbose_name='Employee')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indicators', to='planning_measurements.goal', verbose_name='Goal')),
            ],
            options={
                'verbose_name': 'Indicator',
                'verbose_name_plural': 'Indicators',
                'ordering': ('-calculation_date', 'indicator_id'),
            },
        ),
    ]
