# Generated by Django 6.1 on 2026-09-30 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_traceability', '0001_initial'),
        ('registration_validation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitment',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commitments', to='registration_validation.activity', verbose_name='Activity reference'),
        ),
        migrations.RemoveField(
            model_name='commitment',
            name='evidence',
        ),
        migrations.AddField(
            model_name='commitment',
            name='origin',
            field=models.CharField(default='', max_length=150, verbose_name='Origin'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='Evidence',
        ),
    ]
