# Generated by Django 6.1 on 2026-09-29 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('organization', '0007_alter_employee_delegation_alter_employee_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='delegation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_profiles', to='organization.delegation'),
        ),
    ]
