# Generated by Django 6.1 on 2026-10-07 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_delegation'),
        ('organization', '0007_alter_employee_delegation_alter_employee_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_profile', to='organization.employee', verbose_name='Funcionario'),
        ),
    ]
